### ISSUE TITLE
--watch leads to "can't convert nil into String (TypeError)"

### ISSUE THREAD

**Issue by srid** [xorcery/coyote#10]
on mac lion with default ruby,

```
→ coyote --watch less/main.less:static/main.css 
/Library/Ruby/Gems/1.8/gems/coyote-1.2.1/lib/coyote/bundles.rb:15:in `extname': can't convert nil into String (TypeError)
    from /Library/Ruby/Gems/1.8/gems/coyote-1.2.1/lib/coyote/bundles.rb:15:in `choose'
    from /Library/Ruby/Gems/1.8/gems/coyote-1.2.1/lib/coyote/bundles.rb:9:in `new'
    from /Library/Ruby/Gems/1.8/gems/coyote-1.2.1/lib/coyote/compiler.rb:13:in `initialize'
    from /Library/Ruby/Gems/1.8/gems/coyote-1.2.1/lib/coyote.rb:9:in `new'
    from /Library/Ruby/Gems/1.8/gems/coyote-1.2.1/lib/coyote.rb:9:in `compile'
    from /Library/Ruby/Gems/1.8/gems/coyote-1.2.1/lib/coyote/cli.rb:17
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:55:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:55:in `require'
    from /Library/Ruby/Gems/1.8/gems/coyote-1.2.1/bin/coyote:6
    from /usr/bin/coyote:19:in `load'
    from /usr/bin/coyote:19
```

**Comment by srid** [comment]
i tried `coyote --watch 1 less/main.less:static/main.css` which works, but then nothing happens when the file is changed.

**Comment by caseyohara** [comment]
@srid Try this: `coyote less/main.less:static/main.css --watch`

**Comment by srid** [comment]
hmm, doesn't work:

```
→ coyote less/main.less:static/main.css --watch
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:451:in
`parse': missing argument: --watch (OptionParser::MissingArgument)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1266:in
`parse_in_order'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1254:in
`catch'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1254:in
`parse_in_order'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1248:in
`order!'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1339:in
`permute!'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1360:in
`parse!'
    from /Library/Ruby/Gems/1.8/gems/coyote-1.2.1/lib/coyote/cli.rb:4
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:55:in
`gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:55:in `require'
    from /Library/Ruby/Gems/1.8/gems/coyote-1.2.1/bin/coyote:6
    from /usr/bin/coyote:19:in `load'
    from /usr/bin/coyote:19
```

**Comment by caseyohara** [comment]
@srid what do you get when you run `which lessc`?

**Comment by srid** [comment]
```
→ which lessc
/usr/local/bin/lessc
→ head -n 3 /usr/local/bin/lessc
#!/usr/bin/env node

var path = require('path'),
→ which node
/usr/local/bin/node
```

**Comment by benlumley** [comment]
I get the same error - but it works if i give --watch and -w ?! Odd!

**Comment by caseyohara** [comment]
@benlumley What is the full command you are using?

**Comment by benlumley** [comment]
Works:  

coyote myfile.less:output.css --watch -w

Both break:

coyote myfile.less:output.css --watch

coyote myfile.less:output.css -w

Hope that's helpful - makes no difference where the -w and --watch are btw.

Ben

**Comment by caseyohara** [comment]
Interesting. Let me see if I can reproduce it.

**Comment by darky** [comment]
+1 it's work only with both flags: -w and --watch for less
lol

**Comment by caseyohara** [comment]
@darrrk Try using http://github.com/imulus/banshee. It is a Node version of Coyote (same command line interface) with some new features and it's about 5x faster.

**Comment by darky** [comment]
Thanks, ok =)

**Comment by chrisl8888** [comment]
Any chance that you'll get this problem fixed? I really like this project over some others.

**Comment by BruceClark** [comment]
Hey Chris, 

We recommend checking out banshee, per Casey's recommendation on the post above. https://github.com/imulus/banshee
