### ISSUE TITLE
Watch fails in OS X

### ISSUE THREAD

**Issue by andrefreitas** [xorcery/coyote#12]
> coyote --watch report/static/coffee/:report/static/build/app.min.js   frontend [adb4532] deleted modified untracked
- /Users/afreitas/dev/webservices/report/report/static/coffee/app2.coffee
- /Users/afreitas/dev/webservices/report/report/static/coffee/app.coffee
  11:57:26      Saved bundle to report/static/build/app.min.js   [2 files] [0.0004 sec]
  /Users/afreitas/.rvm/gems/ruby-2.2.3/gems/coyote-1.2.0/lib/coyote/fs_listeners.rb:31:in `mac?': uninitialized constant Coyote::FSListeners::Config (NameError)
  from /Users/afreitas/.rvm/gems/ruby-2.2.3/gems/coyote-1.2.0/lib/coyote/fs_listeners.rb:18:in`choose'
  from /Users/afreitas/.rvm/gems/ruby-2.2.3/gems/coyote-1.2.0/lib/coyote/fs_listeners.rb:12:in `new'
  from /Users/afreitas/.rvm/gems/ruby-2.2.3/gems/coyote-1.2.0/lib/coyote/compiler.rb:35:in`watch'
  from /Users/afreitas/.rvm/gems/ruby-2.2.3/gems/coyote-1.2.0/lib/coyote/compiler.rb:19:in `compile!'
  from /Users/afreitas/.rvm/gems/ruby-2.2.3/gems/coyote-1.2.0/lib/coyote.rb:9:in`compile'
  from /Users/afreitas/.rvm/gems/ruby-2.2.3/gems/coyote-1.2.0/lib/coyote/cli.rb:17:in `<top (required)>'
  from /Users/afreitas/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
  from /Users/afreitas/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from /Users/afreitas/.rvm/gems/ruby-2.2.3/gems/coyote-1.2.0/bin/coyote:6:in`<top (required)>'
  from /Users/afreitas/.rvm/gems/ruby-2.2.3/bin/coyote:23:in `load'
  from /Users/afreitas/.rvm/gems/ruby-2.2.3/bin/coyote:23:in`<main>'
  from /Users/afreitas/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
  from /Users/afreitas/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in`<main>'

**Comment by andrefreitas** [comment]
This is with the latest version deploy in rubygems. I checked that this error is now fixed in this commit: https://github.com/imulus/coyote/commit/552ee42ad1166d0552e2a7aeedd6356fe5e5be91
